# Dependencies
markdown:         kramdown
highlighter:      pygments

kramdown:
  input: GFM
  hard_wrap: false

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
name:             Brendan Hay
title:            Brendan Hay
url:              http://brendanhay.nz
baseurl:          /

author:
  name:           'Brendan Hay'
  url:            https://brendanhay.nz

paginate:         5

permalink:        ':title'
